import cron from 'node-cron';
import fs from 'fs';
import path from 'path';
import { executeWindowsCommand, getWindowsSystemHealth } from '../tools/windowsControl.js';
import { config } from '../config/index.js';

const statusFilePath = path.resolve(process.cwd(), 'logs', 'bot_status.md');

/**
 * Generate daily status pulse report and auto-commit to GitHub
 */
export async function performDailyAutoCommit(): Promise<string> {
  try {
    const logsDir = path.dirname(statusFilePath);
    if (!fs.existsSync(logsDir)) {
      fs.mkdirSync(logsDir, { recursive: true });
    }

    const now = new Date();
    const dateStr = now.toISOString().split('T')[0];
    const timeStr = now.toLocaleTimeString('en-GB', { timeZone: 'Africa/Nairobi' });
    const health = await getWindowsSystemHealth();

    const reportContent = `# 🟢 Astra AI Agent - Daily Status Pulse

**Last Updated:** ${dateStr} at ${timeStr} (EAT)  
**Host Machine:** Windows 11 PC (Local Home Server)  
**Bot Status:** Active & Online (\`@fv_rzkbot\`)  

---

### 📊 System Diagnostics
\`\`\`text
${health}
\`\`\`

---

### 🛡️ Security & Integrity
- **Auth Guard:** Enabled (Restricted to Owner Telegram ID)
- **Engine:** Google Gemini 3.6 Flash + OpenAI Backup
- **Automated Commit:** Heartbeat active via Cron Daemon

---
*Auto-generated by Astra Autonomous OS Daemon.*
`;

    fs.writeFileSync(statusFilePath, reportContent, 'utf-8');

    // Execute git add, commit, and push
    await executeWindowsCommand('git add logs/bot_status.md');
    await executeWindowsCommand(`git commit -m "chore(auto): daily bot status pulse update [${dateStr}]"`);
    await executeWindowsCommand('git push origin HEAD');

    console.log(`✅ [Auto-Commit Success]: Daily status pulse committed and pushed for ${dateStr}`);
    return `Daily status pulse generated and pushed to GitHub for ${dateStr}.`;
  } catch (error: any) {
    console.error('Error performing auto-commit:', error.message);
    return `Auto-commit error: ${error.message}`;
  }
}

/**
 * Initialize 24-hour auto-commit cron job
 */
export function initAutoCommitScheduler() {
  console.log('🔄 Auto-Commit Daemon initialized (runs daily at 00:00 EAT).');
  cron.schedule('0 0 * * *', async () => {
    console.log('⏰ Running daily automatic status commit...');
    await performDailyAutoCommit();
  });
}
